# Dependencies
markdown:           kramdown
highlighter:        rouge

kramdown:
  auto_ids:         true

# Permalinks
permalink:          pretty

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
    style:          compressed

# Setup
title:              "Bootstrap Blog"
description:        "Official blog for the Bootstrap framework."
url:                "https://blog.getbootstrap.com"

# Server
source:             "."
destination:        ./_site
host:               "localhost"
port:               4000
#baseurl:            ""
encoding:           UTF-8

pagination:
  enabled:          true
  per_page:         5
  permalink:        "/page:num/"
  title:            "Page :num of :max"
  limit:            0
  sort_field:       "date"
  sort_reverse:     true

future:             true

exclude:
  - .sass-cache
  - vendor/
  - Gemfile
  - Gemfile.lock
  - netlify.toml
  - README.md

# Links
main:               "https://getbootstrap.com"
expo:               "https://expo.getbootstrap.com"
themes:             "https://themes.getbootstrap.com"

# Social
twitter:            getbootstrap
authors:            "Mark Otto, Jacob Thornton, and Bootstrap contributors"
social_logo_path:   /assets/img/bootstrap-social-logo.png
social_image_path:  /assets/img/bootstrap-social.png
